#!/usr/bin/env python3
"""Fetch GitHub repo metadata and write _data/repositories_meta.yml.

Usage:
    python tools/fetch_repos.py [--token YOUR_GITHUB_TOKEN]

A token is optional but raises the rate limit from 60 to 5000 req/hour.
Without a token the 19 repos still fit comfortably within the 60-req limit.
"""
from __future__ import annotations

import argparse
import ssl
import sys
import urllib.request
import urllib.error
import json
from pathlib import Path

# Windows often lacks the CA bundle needed for GitHub's cert.
# This context is used only for outbound HTTPS to api.github.com.
_SSL_CTX = ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode = ssl.CERT_NONE

REPOS_YML   = Path(__file__).parent.parent / "_data" / "repositories.yml"
OUTPUT_YML  = Path(__file__).parent.parent / "_data" / "repositories_meta.yml"
API_BASE    = "https://api.github.com/repos"


def load_repo_list() -> list[str]:
    """Read dessertlab/repo-name entries from repositories.yml."""
    repos: list[str] = []
    in_list = False
    for line in REPOS_YML.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("github_repos:"):
            in_list = True
            continue
        if in_list and stripped.startswith("- "):
            repos.append(stripped[2:].strip())
    return repos


def fetch(slug: str, token: str | None) -> dict:
    url = f"{API_BASE}/{slug}"
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "dessert-fetch-repos/1.0")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=10, context=_SSL_CTX) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        print(f"  WARNING: {slug} -> HTTP {e.code}", file=sys.stderr)
        return {}
    except Exception as e:
        print(f"  WARNING: {slug} -> {e}", file=sys.stderr)
        return {}


def fetch_languages(slug: str, token: str | None) -> list[str]:
    """Return languages sorted by bytes descending (GitHub /languages endpoint)."""
    url = f"{API_BASE}/{slug}/languages"
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "dessert-fetch-repos/1.0")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=10, context=_SSL_CTX) as resp:
            data: dict = json.loads(resp.read().decode())
            return [lang for lang, _ in sorted(data.items(), key=lambda x: x[1], reverse=True)]
    except Exception as e:
        print(f"  WARNING: {slug} /languages -> {e}", file=sys.stderr)
        return []


def yaml_str(value: str | None) -> str:
    """Emit a YAML single-quoted string, escaping single quotes."""
    if not value:
        return "''"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--token", default=None, help="GitHub personal access token")
    args = parser.parse_args()

    repos = load_repo_list()
    print(f"Fetching metadata for {len(repos)} repositories …")

    lines = ["# Auto-generated by tools/fetch_repos.py — do not edit by hand.",
             "# Re-run the script before building to refresh stars/descriptions.",
             "repos:"]

    for slug in repos:
        print(f"  {slug} …", end=" ", flush=True)
        data = fetch(slug, args.token)
        langs = fetch_languages(slug, args.token)
        owner, name = slug.split("/", 1)
        description = data.get("description") or ""
        language    = langs[0] if langs else (data.get("language") or "")
        stars       = int(data.get("stargazers_count") or 0)
        html_url    = data.get("html_url") or f"https://github.com/{slug}"
        print(f"★ {stars}")
        lines.append(f"  - slug:        {yaml_str(slug)}")
        lines.append(f"    owner:       {yaml_str(owner)}")
        lines.append(f"    name:        {yaml_str(name)}")
        lines.append(f"    description: {yaml_str(description)}")
        lines.append(f"    language:    {yaml_str(language)}")
        if langs:
            langs_yaml = "[" + ", ".join(yaml_str(l) for l in langs) + "]"
            lines.append(f"    languages:   {langs_yaml}")
        lines.append(f"    stars:       {stars}")
        lines.append(f"    url:         {yaml_str(html_url)}")

    OUTPUT_YML.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWritten to {OUTPUT_YML}")


if __name__ == "__main__":
    main()
